[build]
builder = "nixpacks"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "always"

[[services]]
name = "claude-proxy-server"
source = "."

[services.variables]
NODE_ENV = "production"
PORT = "3000"

[services.healthcheck]
path = "/health"
interval = 30
timeout = 10
retries = 3